name: 'Weather Update'
on:
  schedule:
    - cron: '*/10 * * * *'  # 每十分钟运行一次
  workflow_dispatch:  # 手动触发
jobs:
  weather:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Install dependencies'
        run: pip install requests beautifulsoup4
      - name: 'Run weather script'
        run: python weather.py
      - name: 'Commit changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 这里自动生成的密码
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add tenForecast.txt
          git commit -m 'Update weather forecast' || echo "No changes to commit"
          git push https://github:$GITHUB_TOKEN@github.com/microkbcrt/gzautoweather.git HEAD:main
