name: 'Weather Update'
on:
  schedule:
    - cron: '*/10 * * * *'  # 每两分钟运行一次
  workflow_dispatch:  # 手动触发
jobs:
  weather:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Install dependencies'
        run: pip install requests beautifulsoup4
      - name: 'Run weather script'
        run: python weather.py
      - name: 'Commit changes'
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add tenForecast.txt
          git commit -m 'Update weather forecast'
          git push https://github-actions:${{ secrets.ACTIONS_TOKEN }}@github.com/microkbcrt/gzautoweather.git HEAD:main  # 推送到 main 分支
